#!/bin/sh

LIBFILE=builds/jasmine-node/LiveCollection.js
SPECFILE=builds/jasmine-node/LiveCollection.spec.js

coffee -b -c -p src/core.coffee > $LIBFILE
echo "exports.Mutable = Mutable;" >> $LIBFILE
echo "exports.addMethod = addMethod;" >> $LIBFILE
echo "exports.addMutator = addMutator;" >> $LIBFILE

echo "var LiveCollection = require('./LiveCollection');" > $SPECFILE

coffee -b -c -p spec/core.spec.coffee >> $SPECFILE
